# permissions to approve all certmanager.step.sm requests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-approve:self-signed-issuer-chaos-ch
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - signers
  verbs:
  - approve
  resourceNames:
  - chaosissuers.self-signed-issuer.chaos.ch/*
  - chaosclusterissuers.self-signed-issuer.chaos.ch/*