# permissions for end users to edit chaosclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chaosclusterissuer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: venafi-test-wizard
    app.kubernetes.io/part-of: venafi-test-wizard
    app.kubernetes.io/managed-by: kustomize
  name: chaosclusterissuer-editor-role
rules:
- apiGroups:
  - certmanager.chaos.ch
  resources:
  - chaosclusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.chaos.ch
  resources:
  - chaosclusterissuers/status
  verbs:
  - get
