# permissions for end users to edit chaosclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosclusterissuer-editor-role
rules:
- apiGroups:
  - self-signed-issuer.chaos.ch
  resources:
  - chaosclusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self-signed-issuer.chaos.ch
  resources:
  - chaosclusterissuers/status
  verbs:
  - get
