# permissions for end users to edit chaosissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosissuer-editor-role
rules:
- apiGroups:
  - self-signed-issuer.chaos.ch
  resources:
  - chaosissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self-signed-issuer.chaos.ch
  resources:
  - chaosissuers/status
  verbs:
  - get
