# permissions for end users to view chaosclusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosclusterissuer-viewer-role
rules:
- apiGroups:
  - self-signed-issuer.chaos.ch
  resources:
  - chaosclusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - self-signed-issuer.chaos.ch
  resources:
  - chaosclusterissuers/status
  verbs:
  - get
