# permissions for end users to view chaosissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosissuer-viewer-role
rules:
- apiGroups:
  - self-signed-issuer.chaos.ch
  resources:
  - chaosissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - self-signed-issuer.chaos.ch
  resources:
  - chaosissuers/status
  verbs:
  - get
