# permissions for end users to edit chaosissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: chaosissuer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: venafi-test-wizard
    app.kubernetes.io/part-of: venafi-test-wizard
    app.kubernetes.io/managed-by: kustomize
  name: chaosissuer-editor-role
rules:
- apiGroups:
  - self-signed-issuer.chaos.ch
  resources:
  - chaosissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self-signed-issuer.chaos.ch
  resources:
  - chaosissuers/status
  verbs:
  - get
