apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mark1
spec:
  isCA: true
  commonName: certificate-by-chaos-issuer.chaos.ch
  secretName: certificate-by-chaos-issuer
  duration: 4m
  renewBefore: 2m
  dnsNames:
    - example.chaos.test
  issuerRef:
    name: chaosissuer-scenario
    group: self-signed-issuer.chaos.ch
    kind: ChaosIssuer
